[package]
name = "mongo-visual"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = { version = "2.8", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] } 
once_cell = "1.17"
futures = "0.3"
dotenv = "0.15"
